/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ConversationId = IDL.Nat;
export const AiModel = IDL.Variant({
  'claude' : IDL.Null,
  'grok' : IDL.Null,
  'deepseekV3' : IDL.Null,
  'gpt4o' : IDL.Null,
});
export const MessageId = IDL.Nat;
export const CreateConversationArgs = IDL.Record({
  'model' : AiModel,
  'title' : IDL.Text,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'model' : AiModel,
  'title' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'messageCount' : IDL.Nat,
});
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
  'system' : IDL.Null,
});
export const AttachmentKind = IDL.Variant({
  'pdf' : IDL.Null,
  'generatedImage' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const Attachment = IDL.Record({
  'kind' : AttachmentKind,
  'name' : IDL.Text,
  'mimeType' : IDL.Text,
  'storageId' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'model' : IDL.Opt(AiModel),
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : MessageRole,
  'conversationId' : ConversationId,
  'attachments' : IDL.Vec(Attachment),
});
export const ConversationDetail = IDL.Record({
  'id' : ConversationId,
  'model' : AiModel,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const SendMessageArgs = IDL.Record({
  'content' : IDL.Text,
  'conversationId' : ConversationId,
  'attachments' : IDL.Vec(Attachment),
});
export const UpdateConversationArgs = IDL.Record({
  'model' : IDL.Opt(AiModel),
  'title' : IDL.Opt(IDL.Text),
  'conversationId' : ConversationId,
});

export const idlService = IDL.Service({
  'appendAssistantMessage' : IDL.Func(
      [ConversationId, IDL.Text, AiModel],
      [IDL.Opt(MessageId)],
      [],
    ),
  'createConversation' : IDL.Func([CreateConversationArgs], [Conversation], []),
  'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
  'getConversation' : IDL.Func(
      [ConversationId],
      [IDL.Opt(ConversationDetail)],
      ['query'],
    ),
  'listConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'sendMessage' : IDL.Func([SendMessageArgs], [IDL.Opt(MessageId)], []),
  'updateConversation' : IDL.Func([UpdateConversationArgs], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ConversationId = IDL.Nat;
  const AiModel = IDL.Variant({
    'claude' : IDL.Null,
    'grok' : IDL.Null,
    'deepseekV3' : IDL.Null,
    'gpt4o' : IDL.Null,
  });
  const MessageId = IDL.Nat;
  const CreateConversationArgs = IDL.Record({
    'model' : AiModel,
    'title' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'model' : AiModel,
    'title' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'messageCount' : IDL.Nat,
  });
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
    'system' : IDL.Null,
  });
  const AttachmentKind = IDL.Variant({
    'pdf' : IDL.Null,
    'generatedImage' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const Attachment = IDL.Record({
    'kind' : AttachmentKind,
    'name' : IDL.Text,
    'mimeType' : IDL.Text,
    'storageId' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'model' : IDL.Opt(AiModel),
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : MessageRole,
    'conversationId' : ConversationId,
    'attachments' : IDL.Vec(Attachment),
  });
  const ConversationDetail = IDL.Record({
    'id' : ConversationId,
    'model' : AiModel,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const SendMessageArgs = IDL.Record({
    'content' : IDL.Text,
    'conversationId' : ConversationId,
    'attachments' : IDL.Vec(Attachment),
  });
  const UpdateConversationArgs = IDL.Record({
    'model' : IDL.Opt(AiModel),
    'title' : IDL.Opt(IDL.Text),
    'conversationId' : ConversationId,
  });
  
  return IDL.Service({
    'appendAssistantMessage' : IDL.Func(
        [ConversationId, IDL.Text, AiModel],
        [IDL.Opt(MessageId)],
        [],
      ),
    'createConversation' : IDL.Func(
        [CreateConversationArgs],
        [Conversation],
        [],
      ),
    'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
    'getConversation' : IDL.Func(
        [ConversationId],
        [IDL.Opt(ConversationDetail)],
        ['query'],
      ),
    'listConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'sendMessage' : IDL.Func([SendMessageArgs], [IDL.Opt(MessageId)], []),
    'updateConversation' : IDL.Func([UpdateConversationArgs], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };