/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AiModel = { 'claude' : null } |
  { 'grok' : null } |
  { 'deepseekV3' : null } |
  { 'gpt4o' : null };
export interface Attachment {
  'kind' : AttachmentKind,
  'name' : string,
  'mimeType' : string,
  'storageId' : string,
}
export type AttachmentKind = { 'pdf' : null } |
  { 'generatedImage' : null } |
  { 'text' : null } |
  { 'image' : null };
export interface Conversation {
  'id' : ConversationId,
  'model' : AiModel,
  'title' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'messageCount' : bigint,
}
export interface ConversationDetail {
  'id' : ConversationId,
  'model' : AiModel,
  'title' : string,
  'messages' : Array<Message>,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type ConversationId = bigint;
export interface CreateConversationArgs { 'model' : AiModel, 'title' : string }
export interface Message {
  'id' : MessageId,
  'model' : [] | [AiModel],
  'content' : string,
  'createdAt' : Timestamp,
  'role' : MessageRole,
  'conversationId' : ConversationId,
  'attachments' : Array<Attachment>,
}
export type MessageId = bigint;
export type MessageRole = { 'user' : null } |
  { 'assistant' : null } |
  { 'system' : null };
export interface SendMessageArgs {
  'content' : string,
  'conversationId' : ConversationId,
  'attachments' : Array<Attachment>,
}
export type Timestamp = bigint;
export interface UpdateConversationArgs {
  'model' : [] | [AiModel],
  'title' : [] | [string],
  'conversationId' : ConversationId,
}
export type UserId = Principal;
export interface _SERVICE {
  'appendAssistantMessage' : ActorMethod<
    [ConversationId, string, AiModel],
    [] | [MessageId]
  >,
  'createConversation' : ActorMethod<[CreateConversationArgs], Conversation>,
  'deleteConversation' : ActorMethod<[ConversationId], boolean>,
  'getConversation' : ActorMethod<[ConversationId], [] | [ConversationDetail]>,
  'listConversations' : ActorMethod<[], Array<Conversation>>,
  'sendMessage' : ActorMethod<[SendMessageArgs], [] | [MessageId]>,
  'updateConversation' : ActorMethod<[UpdateConversationArgs], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];