/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ConversationDetail {
    id: ConversationId;
    model: AiModel;
    title: string;
    messages: Array<Message>;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export interface SendMessageArgs {
    content: string;
    conversationId: ConversationId;
    attachments: Array<Attachment>;
}
export interface CreateConversationArgs {
    model: AiModel;
    title: string;
}
export type ConversationId = bigint;
export type UserId = Principal;
export type MessageId = bigint;
export interface UpdateConversationArgs {
    model?: AiModel;
    title?: string;
    conversationId: ConversationId;
}
export interface Message {
    id: MessageId;
    model?: AiModel;
    content: string;
    createdAt: Timestamp;
    role: MessageRole;
    conversationId: ConversationId;
    attachments: Array<Attachment>;
}
export interface Attachment {
    kind: AttachmentKind;
    name: string;
    mimeType: string;
    storageId: string;
}
export interface Conversation {
    id: ConversationId;
    model: AiModel;
    title: string;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    messageCount: bigint;
}
export enum AiModel {
    claude = "claude",
    grok = "grok",
    deepseekV3 = "deepseekV3",
    gpt4o = "gpt4o"
}
export enum AttachmentKind {
    pdf = "pdf",
    generatedImage = "generatedImage",
    text = "text",
    image = "image"
}
export enum MessageRole {
    user = "user",
    assistant = "assistant",
    system = "system"
}
export interface backendInterface {
    appendAssistantMessage(conversationId: ConversationId, content: string, model: AiModel): Promise<MessageId | null>;
    createConversation(args: CreateConversationArgs): Promise<Conversation>;
    deleteConversation(conversationId: ConversationId): Promise<boolean>;
    getConversation(conversationId: ConversationId): Promise<ConversationDetail | null>;
    listConversations(): Promise<Array<Conversation>>;
    sendMessage(args: SendMessageArgs): Promise<MessageId | null>;
    updateConversation(args: UpdateConversationArgs): Promise<boolean>;
}
import type { AiModel as _AiModel, Attachment as _Attachment, AttachmentKind as _AttachmentKind, Conversation as _Conversation, ConversationDetail as _ConversationDetail, ConversationId as _ConversationId, CreateConversationArgs as _CreateConversationArgs, Message as _Message, MessageId as _MessageId, MessageRole as _MessageRole, SendMessageArgs as _SendMessageArgs, Timestamp as _Timestamp, UpdateConversationArgs as _UpdateConversationArgs, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async appendAssistantMessage(arg0: ConversationId, arg1: string, arg2: AiModel): Promise<MessageId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.appendAssistantMessage(arg0, arg1, to_candid_AiModel_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.appendAssistantMessage(arg0, arg1, to_candid_AiModel_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createConversation(arg0: CreateConversationArgs): Promise<Conversation> {
        if (this.processError) {
            try {
                const result = await this.actor.createConversation(to_candid_CreateConversationArgs_n4(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Conversation_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConversation(to_candid_CreateConversationArgs_n4(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Conversation_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteConversation(arg0: ConversationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConversation(arg0);
            return result;
        }
    }
    async getConversation(arg0: ConversationId): Promise<ConversationDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConversations();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConversations();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: SendMessageArgs): Promise<MessageId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(to_candid_SendMessageArgs_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(to_candid_SendMessageArgs_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateConversation(arg0: UpdateConversationArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConversation(to_candid_UpdateConversationArgs_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConversation(to_candid_UpdateConversationArgs_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AiModel_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AiModel): AiModel {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_AttachmentKind_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttachmentKind): AttachmentKind {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Attachment_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attachment): Attachment {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ConversationDetail_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationDetail): ConversationDetail {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Conversation_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_MessageRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageRole): MessageRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ConversationDetail]): ConversationDetail | null {
    return value.length === 0 ? null : from_candid_ConversationDetail_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AiModel]): AiModel | null {
    return value.length === 0 ? null : from_candid_AiModel_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MessageId]): MessageId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConversationId;
    model: _AiModel;
    title: string;
    messages: Array<_Message>;
    userId: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
}): {
    id: ConversationId;
    model: AiModel;
    title: string;
    messages: Array<Message>;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        model: from_candid_AiModel_n8(_uploadFile, _downloadFile, value.model),
        title: value.title,
        messages: from_candid_vec_n13(_uploadFile, _downloadFile, value.messages),
        userId: value.userId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    model: [] | [_AiModel];
    content: string;
    createdAt: _Timestamp;
    role: _MessageRole;
    conversationId: _ConversationId;
    attachments: Array<_Attachment>;
}): {
    id: MessageId;
    model?: AiModel;
    content: string;
    createdAt: Timestamp;
    role: MessageRole;
    conversationId: ConversationId;
    attachments: Array<Attachment>;
} {
    return {
        id: value.id,
        model: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.model)),
        content: value.content,
        createdAt: value.createdAt,
        role: from_candid_MessageRole_n17(_uploadFile, _downloadFile, value.role),
        conversationId: value.conversationId,
        attachments: from_candid_vec_n19(_uploadFile, _downloadFile, value.attachments)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kind: _AttachmentKind;
    name: string;
    mimeType: string;
    storageId: string;
}): {
    kind: AttachmentKind;
    name: string;
    mimeType: string;
    storageId: string;
} {
    return {
        kind: from_candid_AttachmentKind_n22(_uploadFile, _downloadFile, value.kind),
        name: value.name,
        mimeType: value.mimeType,
        storageId: value.storageId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConversationId;
    model: _AiModel;
    title: string;
    userId: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    messageCount: bigint;
}): {
    id: ConversationId;
    model: AiModel;
    title: string;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    messageCount: bigint;
} {
    return {
        id: value.id,
        model: from_candid_AiModel_n8(_uploadFile, _downloadFile, value.model),
        title: value.title,
        userId: value.userId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        messageCount: value.messageCount
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
} | {
    system: null;
}): MessageRole {
    return "user" in value ? MessageRole.user : "assistant" in value ? MessageRole.assistant : "system" in value ? MessageRole.system : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    generatedImage: null;
} | {
    text: null;
} | {
    image: null;
}): AttachmentKind {
    return "pdf" in value ? AttachmentKind.pdf : "generatedImage" in value ? AttachmentKind.generatedImage : "text" in value ? AttachmentKind.text : "image" in value ? AttachmentKind.image : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    claude: null;
} | {
    grok: null;
} | {
    deepseekV3: null;
} | {
    gpt4o: null;
}): AiModel {
    return "claude" in value ? AiModel.claude : "grok" in value ? AiModel.grok : "deepseekV3" in value ? AiModel.deepseekV3 : "gpt4o" in value ? AiModel.gpt4o : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attachment>): Array<Attachment> {
    return value.map((x)=>from_candid_Attachment_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n6(_uploadFile, _downloadFile, x));
}
function to_candid_AiModel_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AiModel): _AiModel {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AttachmentKind_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttachmentKind): _AttachmentKind {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_Attachment_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Attachment): _Attachment {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_CreateConversationArgs_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateConversationArgs): _CreateConversationArgs {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_SendMessageArgs_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SendMessageArgs): _SendMessageArgs {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateConversationArgs_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateConversationArgs): _UpdateConversationArgs {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    conversationId: ConversationId;
    attachments: Array<Attachment>;
}): {
    content: string;
    conversationId: _ConversationId;
    attachments: Array<_Attachment>;
} {
    return {
        content: value.content,
        conversationId: value.conversationId,
        attachments: to_candid_vec_n27(_uploadFile, _downloadFile, value.attachments)
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kind: AttachmentKind;
    name: string;
    mimeType: string;
    storageId: string;
}): {
    kind: _AttachmentKind;
    name: string;
    mimeType: string;
    storageId: string;
} {
    return {
        kind: to_candid_AttachmentKind_n30(_uploadFile, _downloadFile, value.kind),
        name: value.name,
        mimeType: value.mimeType,
        storageId: value.storageId
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model?: AiModel;
    title?: string;
    conversationId: ConversationId;
}): {
    model: [] | [_AiModel];
    title: [] | [string];
    conversationId: _ConversationId;
} {
    return {
        model: value.model ? candid_some(to_candid_AiModel_n1(_uploadFile, _downloadFile, value.model)) : candid_none(),
        title: value.title ? candid_some(value.title) : candid_none(),
        conversationId: value.conversationId
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model: AiModel;
    title: string;
}): {
    model: _AiModel;
    title: string;
} {
    return {
        model: to_candid_AiModel_n1(_uploadFile, _downloadFile, value.model),
        title: value.title
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AiModel): {
    claude: null;
} | {
    grok: null;
} | {
    deepseekV3: null;
} | {
    gpt4o: null;
} {
    return value == AiModel.claude ? {
        claude: null
    } : value == AiModel.grok ? {
        grok: null
    } : value == AiModel.deepseekV3 ? {
        deepseekV3: null
    } : value == AiModel.gpt4o ? {
        gpt4o: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttachmentKind): {
    pdf: null;
} | {
    generatedImage: null;
} | {
    text: null;
} | {
    image: null;
} {
    return value == AttachmentKind.pdf ? {
        pdf: null
    } : value == AttachmentKind.generatedImage ? {
        generatedImage: null
    } : value == AttachmentKind.text ? {
        text: null
    } : value == AttachmentKind.image ? {
        image: null
    } : value;
}
function to_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Attachment>): Array<_Attachment> {
    return value.map((x)=>to_candid_Attachment_n28(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
